### ISSUE TITLE
NWN.MasterList.Test.Client.TestGetAllElcByType

### ISSUE THREAD

**Issue by milliorn** [nwn-dotnet/NWN.MasterList#17]
https://github.com/milliorn/NWN.MasterList-1/blob/214a37ab8ebf04fd891da46ab8f082304c3f47ec/API/src/Helper.cs#L37-L37

NWN.MasterList.Test.Client.TestGetAllElcByType:
    Outcome: Failed
    Error Message:
    System.InvalidCastException : Unable to cast object of type 'SelectIPartitionIterator`2[NWN.MasterList.Data.NwServer,System.Boolean]' to type 'System.Linq.IOrderedEnumerable`1[NWN.MasterList.Data.NwServer]'.
    Stack Trace:
       at NWN.MasterList.Helper.GetAllElcByType(Client client, Boolean setting) in c:\Users\scott\Desktop\NWN.MasterList-1\API\src\Helper.cs:line 41
   at NWN.MasterList.Test.Client.TestGetAllElcByType() in c:\Users\scott\Desktop\NWN.MasterList-1\Test\src\Client.Test.cs:line 97
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   
```cs
public async static Task<IOrderedEnumerable<NwServer>> GetAllElc(this Client client) =>
	(await client.GetServers()).OrderBy(x => x.ELC).ThenBy(x => x.ModuleName);

  // TODO #17
public async static Task<IOrderedEnumerable<NwServer>> GetAllElcByType(this Client client, bool setting)
{
	var response = await client.GetAllElc();
	return (IOrderedEnumerable<NwServer>)response.Select(x => x.Equals(setting));
}
```
```cs
[Fact]
public async void TestGetAllElcByType()
{
    var collection = await new MasterList.Client().GetAllElcByType(false);

    foreach (var item in collection)
    {
        output.WriteLine($"{item.ModuleName} -> ELC:{item.ELC}");
    }

    Assert.NotEmpty(collection);
    Assert.NotNull(collection);
}
```
There is an issue with `GetAllElcByType` function and how I am casting `(IOrderedEnumerable<NwServer>` result in the return.

**Comment by milliorn** [comment]
Resolved in latest PR. #14

**Comment by milliorn** [comment]
Resolved in latest PR. #14
